Repository validator-labs/validator-plugin-azure, pull requests merged in 2024-12, with the labels that each got.

#318 chore: re-scaffold project
  .golangci.yml
  PROJECT
  api/v1alpha1/azurevalidator_types.go
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/templates/deployment.yaml
  chart/validator-plugin-azure/templates/metrics-auth-rbac.yaml
  chart/validator-plugin-azure/values.yaml
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/manager/manager.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_auth_role.yaml
  config/rbac/metrics_auth_role_binding.yaml
  config/rbac/metrics_reader_role.yaml
  config/samples/kustomization.yaml
  go.mod
  go.sum
  internal/controller/azurevalidator_controller.go
  internal/controller/azurevalidator_controller_test.go
  internal/controller/suite_test.go
  pkg/validate/validate_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/e2e_test.go
  tests/utils/utils.go
Labels: enhancement, size:XXL

#312 chore(main): release 0.0.25
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:S, lgtm

#326 fix: metrics targetPort https -> 8443
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: size:XS, lgtm

#322 chore(main): release 0.0.26
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:S
