Repository validator-labs/validator-plugin-azure, pull requests merged in 2024-11, with the labels that each got.

#272 chore(main): release 0.0.22
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:M

#293 test: controller inline auth test coverage
  Dockerfile
  Dockerfile.devspace
  go.mod
  internal/controller/azurevalidator_controller_test.go
Labels: enhancement, size:L, lgtm

#302 fix: make inline auth work in direct mode too
  go.mod
  internal/controller/azurevalidator_controller.go
  internal/controller/azurevalidator_controller_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: bug, size:XL, lgtm

#291 chore(main): release 0.0.23
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:M

#310 fix: setting auth env vars
  pkg/validate/validate.go
Labels: bug, size:S, lgtm

#307 chore(main): release 0.0.24
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:S
