Repository validator-labs/validator-plugin-azure, pull requests merged in 2024-07, with the labels that each got.

#154 chore(main): release 0.0.12
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending

#193 chore(main): release 0.0.13
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:S, lgtm

#211 deps(deps): update module github.com/azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5 to v6
  go.mod
  go.sum
  internal/utils/azure/azure.go
  internal/validators/community_image.go
  internal/validators/community_image_test.go
Labels: size:XS

#201 chore(main): release 0.0.14
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: documentation, autorelease: pending, size:S
