Repository validator-labs/validator-plugin-azure, pull requests merged in 2024-08, with the labels that each got.

#222 docs: principal ID and rules in readme
  README.md
  api/v1alpha1/azurevalidator_types.go
  chart/validator-plugin-azure/crds/validation.spectrocloud.labs_azurevalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_azurevalidators.yaml
Labels: documentation, size:M, lgtm

#223 chore: remove unused helm value
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: size:XS

#225 refactor: support direct rule evaluation
  api/v1alpha1/azurevalidator_types.go
  go.mod
  go.sum
  internal/controller/azurevalidator_controller.go
  internal/controller/azurevalidator_controller_test.go
  pkg/azure/community_image.go
  pkg/azure/community_image_test.go
  pkg/azure/rbac.go
  pkg/azure/rbac_permissions.go
  pkg/azure/rbac_permissions_test.go
  pkg/azure/rbac_test.go
  pkg/constants/constants.go
  pkg/utils/azure/azure.go
  pkg/utils/azure/azure_test.go
  pkg/utils/azureerrors/errors.go
  pkg/utils/maps/maps.go
  pkg/utils/maps/maps_test.go
  pkg/validate/validate.go
Labels: enhancement, size:L

#226 refactor: return error from validate, accept context
  internal/controller/azurevalidator_controller.go
  pkg/validate/validate.go
Labels: enhancement, size:S

#218 chore(main): release 0.0.15
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:M

#228 refactor: do not return an error from Validate
  internal/controller/azurevalidator_controller.go
  pkg/validate/validate.go
Labels: enhancement, size:S

#233 chore: satisfy ValidationRule
  api/v1alpha1/azurevalidator_types.go
  go.mod
  go.sum
Labels: size:XS

#229 chore(main): release 0.0.16
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:M, lgtm

#245 feat: add support for connecting to Azure Government and Azure in China
  README.md
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/templates/deployment.yaml
  chart/validator-plugin-azure/values.yaml
  devspace.yaml
  pkg/utils/azure/azure.go
Labels: size:M, lgtm, new-feature

#242 chore(main): release 0.0.17
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: documentation, autorelease: pending, size:S

#250 refactor: make each rule implement `validationrule.Interface`
  api/v1alpha1/azurevalidator_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator-plugin-azure/crds/validation.spectrocloud.labs_azurevalidators.yaml
  config/crd/bases/validation.spectrocloud.labs_azurevalidators.yaml
  go.mod
  go.sum
  pkg/azure/community_image.go
  pkg/azure/community_image_test.go
  pkg/azure/rbac.go
  pkg/azure/rbac_test.go
Labels: enhancement, size:M, lgtm

#247 chore(main): release 0.0.18
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:S

#256 fix: embedding structs related to `validationrule.Interface`
  api/v1alpha1/azurevalidator_types.go
Labels: bug, size:XS

#254 chore: assert that PluginSpec is implemented
  api/v1alpha1/azurevalidator_types.go
  go.mod
  go.sum
Labels: size:XS, lgtm

#255 chore(main): release 0.0.19
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: autorelease: pending, size:S

#260 fix: YAML rendering of structs embedded in rules
  api/v1alpha1/azurevalidator_types.go
Labels: bug, size:XS

#261 chore(main): release 0.0.20
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator-plugin-azure/Chart.yaml
  chart/validator-plugin-azure/README.md
  chart/validator-plugin-azure/values.yaml
Labels: bug, autorelease: pending, size:S
